#include <rpc/rpc.h>
/*
 * math.h is generated by rpcgen 
 */  
#include "math.h"
int * add_1_svc (pair, rqstp) 
     intpair * pair;
     struct svc_req *rqstp;

{
  static int result;

  result = pair->a + pair->b;
  return (&result);
}

int * multiply_1_svc (pair, rqstp) 
     intpair * pair;
     struct svc_req *rqstp;

{
  static int result;

  result = pair->a * pair->b;
  return (&result);
}

int * cube_1_svc (base, rqstp)  
     int * base;
     struct svc_req *rqstp;

{
  static int result;
  int baseval = *base;

  result = baseval * baseval * baseval;
  return (&result);
}


